################################################################################
# Node-RED - Mosquitto - MySQL - PHPMyAdmin - Node
################################################################################
# Microservicios para el trabajo práctico de la asignatura Desarrollo de Aplicaciones IoT
# Facultad de Ingeniería - Universidad de Buenos Aires
# Autor: Ing. Martin Acosta - 2020
################################################################################
version: "3"

services:
  node-red:
    container_name: nodered_docker
    image: nodered-daiot:latest
    environment:
      - TZ=Europe/Amsterdam
    ports:
      - "5600:1880"
    networks:
      - daiot-net
  
  mosquitto:
    container_name: mosquitto_docker
    image: eclipse-mosquitto
    ports:
      - "9001:9001"
      - "1884:1883"
    networks:
      - daiot-net
    volumes:
      - "./mosquitto:/mosquitto"
    
  mysql-server:
    image: mysql:5.7
    hostname: mysql-server
    container_name: mysql-server
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: userpass
    volumes:
      - ./db/dumps:/docker-entrypoint-initdb.d
      - ./db/data:/var/lib/mysql
    networks:
      - daiot-net

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    hostname: phpmyadmin
    container_name: phpmyadmin_docker
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: userpass
    networks:
      - daiot-net
    ports:
      - "8085:80"

  node-app:
    image: abassi/nodejs-server:10.0-dev
    container_name: node_docker
    restart: always
    volumes:
      - .:/home/node/app
    networks:
      - daiot-net
    depends_on:
      - mysql-server
    ports:
      - "8000:3000"
    command: nodemon index.js

volumes:
  node-red-data:

networks:
  daiot-net:
    driver: bridge